apiVersion: v1
kind: Service
metadata:
  name: vote-services
  labels:
    app: vote-services
spec:
  type: NodePort 
  ports:
    - name: vote-services
      port: 8080
      targetPort: 80
      nodePort: 31000
  selector:
    app: vote-app