apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-services
  labels:
    app: todo-frontend-services
spec:
   type: NodePort
   ports:
    - name: todo-frontend-services
      port: 3000
      targetPort: 3000
      nodePort: 31000
   selector:
    app: todo-frontend-pod