apiVersion: v1
kind: Pod
metadata:
  name: todo-backend-pod
  labels:
    app: todo-backend-pod
spec:
  containers:
    - name: todo-backend
      image: umarkhan803/todo-backend
      env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGODB_URI
      ports:
        - containerPort: 5000
          name: todo-backend