apiVersion: v1
kind: Pod
metadata:
  name: todo-frontend-pod
  labels:
    app: todo-frontend-pod
spec:
  containers:
    - name: todo-frontend
      image: umarkhan803/todo-frontend
      ports:
      - containerPort: 3000
        name: todo-frontend
